run_time_vars:
- name: PUBLIC_KEY
  source:
    path: api-node/config-input.yaml
    key: public_key
    address_position: 0 
    key_type: public
  targets:
  - rest-gateway/userconfig/rest.json

- name: FRIENDLY_NAME
  source:
    type: friendly_name
    path: api-node/config-input.yaml
    key: friendly_name
    address_position: 0 
    key_type: public
    donot_overwrite: true
  targets:
  - api-node/userconfig/resources/config-node.properties

